import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import cleanupExtraData from "../scripts/cleanupExtraData";

// Call the function immediately (not recommended for production use)
(async () => {
  try {
    console.log("Starting cleanup process...");
    await cleanupExtraData();
    console.log("Cleanup process completed successfully.");
  } catch (error) {
    console.error("Error during cleanup process:", error);
  }
})();
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
